name: CI

on:
  workflow_dispatch:  

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [a,b,c,d,e,f,h,i,j,l]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run
        run: |
          for i in {1..300}
          do
            dd if=/dev/zero of=/dev/null bs=1M count=100
            echo "sl 60000"
            sleep 60
          done
